#!/usr/bin/env python3
"""
l2l1-kit · sync.py — розгортає/оновлює протокол L2/L1 в екосистемі проєктів.

Запуск (з кореня meta-репозиторію екосистеми, де лежить ecosystem.toml):
    python <kit>/sync.py                 # згенерувати/оновити все на цій машині
    python <kit>/sync.py --check         # лише показати, що застаріло (нічого не писати)
    python <kit>/sync.py --no-global     # не чіпати ~/.gemini/config
    python <kit>/sync.py --git-init      # git init + .gitignore/.env.template у підпроєктах без .git
    python <kit>/sync.py --root <path>   # корінь екосистеми, якщо запускаєш не з нього
    python <kit>/sync.py --gemini-config <path>   # якщо ~/.gemini/config не там, де HOME (напр. у VM)
    python <kit>/sync.py --display-root <path> --display-gemini-config <path>   # шляхи, які писати у файли, якщо запуск через mount

Що генерується (перезаписується при кожному sync — НЕ правити руками):
    <root>/CLAUDE.md                        з templates/CLAUDE.md + ecosystem.toml + <root>/claude.extra.md
    <root>/.agents/TASK_TEMPLATE.md         з templates/TASK_TEMPLATE.md
    <root>/.agents/workflows/task.md        з templates/workflows/task.md
    <root>/<P>/.agents/AGENTS.md            з templates/AGENTS.md + <P>/.agents/agents.local.md
    <root>/<P>/.agents/workflows/task.md    з templates/workflows/task.md
    ~/.gemini/config/AGENTS.md              з templates/gemini-global-AGENTS.md   (глобально для машини)
    ~/.gemini/config/skills/<shared skills> з skills/
Що створюється лише якщо відсутнє (далі — проєктне, руками):
    <root>/Global_Context.md, Global_Roadmap.md, Global_Changelog.md, claude.extra.md
    <root>/<P>/.agents/agents.local.md       («Специфіка» підпроєкту; джерело — bootstrap із ecosystem.toml, якщо задано)
    <root>/<P>/.agents/rules/project-rules.md (скелет)
    <root>/<P>/.agents/tasks/done/.gitkeep
Python 3.8+; на 3.11+ використовує tomllib, інакше — вбудований міні-парсер TOML. Залежностей немає.
"""
import argparse, os, sys, shutil, io, datetime, subprocess

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    tomllib = None


def _mini_toml(text):
    """Мінімальний парсер підмножини TOML для ecosystem.toml (Python < 3.11):
    key = "str" | true/false | 123 | ["a", "b"]; секції [[name]]; коментарі #."""
    import re
    root, cur = {}, None
    def val(s):
        s = s.strip()
        if s.startswith('"'):
            return bytes(s[1:s.rindex('"')], "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
        if s.startswith("'"):
            return s[1:s.rindex("'")]
        if s in ("true", "false"):
            return s == "true"
        if s.startswith("["):
            inner = s[1:s.rindex("]")]
            return [val(x) for x in re.findall(r'"(?:[^"\\]|\\.)*"|\'[^\']*\'|[^,\s]+', inner)] if inner.strip() else []
        try:
            return int(s)
        except ValueError:
            return s
    for raw in text.splitlines():
        line = raw.split(" #")[0].strip() if not raw.strip().startswith("#") else ""
        if not line:
            continue
        m = re.match(r"^\[\[(\w+)\]\]$", line)
        if m:
            cur = {}
            root.setdefault(m.group(1), []).append(cur)
            continue
        m = re.match(r"^(\w+)\s*=\s*(.+)$", line)
        if m:
            (cur if cur is not None else root)[m.group(1)] = val(m.group(2))
    return root

KIT = os.path.dirname(os.path.abspath(__file__))
TPL = os.path.join(KIT, "templates")
GEN_MARK = "<!-- GENERATED by l2l1-kit/sync.py from templates/{src} — не правити руками: {local} -->"


def read(p):
    with io.open(p, encoding="utf-8") as f:
        return f.read()


def write(p, content, dry):
    os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
    old = read(p) if os.path.exists(p) else None
    if old == content:
        return "same"
    if not dry:
        with io.open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
    return "updated" if old is not None else "created"


def with_mark(text, src, local):
    mark = GEN_MARK.format(src=src, local=local)
    # frontmatter (---) має лишатися першим — маркер після нього
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            end = end + len("\n---")
            return text[:end] + "\n" + mark + text[end:]
    return mark + "\n" + text


def render(text, mapping):
    for k, v in mapping.items():
        text = text.replace("{{" + k + "}}", v)
    return text


def project_table(cfg, root, sep):
    rows = ["| Підпроєкт | Тег задач | Воркспейс L1 | Holy Trinity | Ціль запуску | Особливі правила |",
            "|---|---|---|---|---|---|"]
    for p in cfg.get("projects", []):
        ws = root + sep + p["dir"]
        hil = " · HIL-gate" if p.get("hil") else ""
        rows.append(f"| {p['title']} | `{p['tag']}` | `{ws}` | `Context_{p['ssot']} / Plan_{p['ssot']} / Changelog_{p['ssot']}` | {p.get('target','—')} | {p.get('rules','—')}{hil} |")
    for p in cfg.get("planned", []):
        rows.append(f"| *(пізніше)* {p['title']} | `{p['tag']}` | `{root}{sep}{p['dir']}` | — | {p.get('target','—')} | {p.get('rules','—')} |")
    note = cfg.get("table_note", "")
    reserved = cfg.get("tags_reserved")
    if reserved:
        note += ("\n\n" if note else "") + "Теги задач унікальні між екосистемами (ліміти Gemini спільні). Зайняті іншими екосистемами: " + ", ".join(f"`{t}`" for t in reserved) + "."
    return "\n".join(rows) + ("\n\n" + note if note else "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.getcwd())
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--no-global", action="store_true")
    ap.add_argument("--git-init", action="store_true")
    ap.add_argument("--gemini-config", default=None, help="шлях до глобального конфігу Gemini (за замовчуванням ~/.gemini/config)")
    ap.add_argument("--display-root", default=None, help="як записувати шлях кореня в згенерованих файлах (якщо запускаєш через mount/VM)")
    ap.add_argument("--display-gemini-config", default=None, help="як записувати шлях конфігу Gemini в згенерованих файлах")
    a = ap.parse_args()
    root = os.path.abspath(a.root)
    cfg_path = os.path.join(root, "ecosystem.toml")
    if not os.path.exists(cfg_path):
        sys.exit(f"Не знайдено {cfg_path}. Запускай з кореня екосистеми або передай --root.")
    if tomllib:
        with open(cfg_path, "rb") as f:
            cfg = tomllib.load(f)
    else:
        cfg = _mini_toml(read(cfg_path))
    dry = a.check
    sep = os.sep
    gemini_cfg = os.path.abspath(a.gemini_config) if a.gemini_config else os.path.join(os.path.expanduser("~"), ".gemini", "config")
    eco = cfg["name"]
    results = []

    droot = a.display_root or root
    dgem = a.display_gemini_config or gemini_cfg
    base = {"ECOSYSTEM": eco, "ROOT": droot, "SEP": sep, "GEMINI_CONFIG": dgem}

    # --- корінь ---
    extra_path = os.path.join(root, "claude.extra.md")
    if not os.path.exists(extra_path):
        results.append((write(extra_path, "<!-- Екосистемні протоколи Архітектора (§6 CLAUDE.md). Кожен пункт — рядок '- **Назва.** …' -->\n", dry), extra_path))
    protocols = read(extra_path).strip() if os.path.exists(extra_path) else ""
    protocols = "\n".join(l for l in protocols.splitlines() if not l.strip().startswith("<!--"))
    claude = render(read(os.path.join(TPL, "CLAUDE.md")), {**base,
                    "PROJECT_TABLE": project_table(cfg, droot, sep),
                    "ECOSYSTEM_PROTOCOLS": protocols})
    results.append((write(os.path.join(root, "CLAUDE.md"), with_mark(claude, "CLAUDE.md", "зміни в kit, ecosystem.toml або claude.extra.md"), dry), "CLAUDE.md"))
    tt = render(read(os.path.join(TPL, "TASK_TEMPLATE.md")), base)
    results.append((write(os.path.join(root, ".agents", "TASK_TEMPLATE.md"), with_mark(tt, "TASK_TEMPLATE.md", "зміни лише в kit"), dry), ".agents/TASK_TEMPLATE.md"))
    wf = with_mark(render(read(os.path.join(TPL, "workflows", "task.md")), base), "workflows/task.md", "зміни лише в kit")
    results.append((write(os.path.join(root, ".agents", "workflows", "task.md"), wf, dry), ".agents/workflows/task.md"))
    for g in ("Global_Context.md", "Global_Roadmap.md", "Global_Changelog.md"):
        gp = os.path.join(root, g)
        if not os.path.exists(gp):
            results.append((write(gp, render(read(os.path.join(TPL, g)), base).replace("YYYY-MM-DD", datetime.date.today().isoformat()), dry), g))

    # --- підпроєкти ---
    for p in cfg.get("projects", []):
        d = os.path.join(root, p["dir"])
        ag = os.path.join(d, ".agents")
        ws = droot + sep + p["dir"]
        local_path = os.path.join(ag, "agents.local.md")
        if not os.path.exists(local_path):
            src = p.get("local")
            content = read(os.path.join(root, src)) if src and os.path.exists(os.path.join(root, src)) else f"\n## Специфіка {p['dir']}\n- …\n"
            results.append((write(local_path, content, dry), f"{p['dir']}/.agents/agents.local.md"))
        extra = read(local_path) if os.path.exists(local_path) else ""
        m = {**base, "P": p["dir"], "TAG": p["tag"], "X": p["ssot"], "TITLE": p["title"], "WS": ws, "EXTRA": "\n" + extra.strip("\n") + "\n"}
        agents = with_mark(render(read(os.path.join(TPL, "AGENTS.md")), m), "AGENTS.md", "зміни в kit або в agents.local.md поруч")
        results.append((write(os.path.join(ag, "AGENTS.md"), agents, dry), f"{p['dir']}/.agents/AGENTS.md"))
        results.append((write(os.path.join(ag, "workflows", "task.md"), wf, dry), f"{p['dir']}/.agents/workflows/task.md"))
        rules = os.path.join(ag, "rules", "project-rules.md")
        if not os.path.exists(rules):
            results.append((write(rules, render(read(os.path.join(TPL, "project-rules.md")), m), dry), f"{p['dir']}/.agents/rules/project-rules.md"))
        keep = os.path.join(ag, "tasks", "done", ".gitkeep")
        if not os.path.exists(keep):
            results.append((write(keep, "", dry), f"{p['dir']}/.agents/tasks/done/.gitkeep"))
        if a.git_init and not dry and not os.path.exists(os.path.join(d, ".git")):
            subprocess.run(["git", "init", "-q", "-b", "main"], cwd=d, check=True)
            gi = os.path.join(d, ".gitignore")
            if not os.path.exists(gi):
                write(gi, ".venv/\nvenv/\n__pycache__/\n*.pyc\n.env\n*.log\n.pytest_cache/\nbuild/\ndist/\n.DS_Store\nThumbs.db\n", False)
            et = os.path.join(d, ".env.template")
            if not os.path.exists(et):
                write(et, "# скопіюй у .env і заповни; .env ніколи не комітиться\n", False)
            results.append(("git-init", p["dir"]))

    # --- глобальний конфіг Gemini на цій машині ---
    if not a.no_global:
        gp = os.path.join(gemini_cfg, "AGENTS.md")
        new = with_mark(render(read(os.path.join(TPL, "gemini-global-AGENTS.md")), base), "gemini-global-AGENTS.md", "зміни лише в kit")
        if os.path.exists(gp) and read(gp) != new and not dry and "GENERATED by l2l1-kit" not in read(gp):
            shutil.copy(gp, gp + ".bak-" + datetime.datetime.now().strftime("%Y%m%d-%H%M"))
        results.append((write(gp, new, dry), gp))
        for s in os.listdir(os.path.join(KIT, "skills")):
            src = os.path.join(KIT, "skills", s, "SKILL.md")
            if os.path.exists(src):
                results.append((write(os.path.join(gemini_cfg, "skills", s, "SKILL.md"), read(src), dry), f"{gemini_cfg}/skills/{s}"))

    # --- звіт ---
    verb = {"same": "  ok      ", "updated": "  UPDATED " if not dry else "  STALE   ", "created": "  CREATED " if not dry else "  MISSING ", "git-init": "  git-init "}
    for st, name in results:
        print(verb.get(st, st) + name)
    changed = [n for st, n in results if st != "same"]
    print(f"\n{eco}: {len(results)} файлів, {'застарілих' if dry else 'змінено'}: {len(changed)}" + (" — запусти без --check, щоб оновити" if dry and changed else ""))
    warn_unpushed([KIT, root])
    return 1 if (dry and changed) else 0


def warn_unpushed(repos):
    """Нагадування: локальна правка протоколу не діє на інших машинах, поки не в origin."""
    import subprocess
    pending = []
    for r in repos:
        try:
            if subprocess.run(["git", "-C", r, "rev-parse", "--git-dir"],
                              capture_output=True).returncode != 0:
                continue
            up = subprocess.run(["git", "-C", r, "rev-parse", "--abbrev-ref", "@{upstream}"],
                                capture_output=True, text=True)
            if up.returncode != 0:
                pending.append((r, "upstream не налаштований"))
                continue
            out = subprocess.run(["git", "-C", r, "log", "--oneline", "@{upstream}..HEAD"],
                                 capture_output=True, text=True).stdout.strip()
            dirty = subprocess.run(["git", "-C", r, "status", "--porcelain"],
                                   capture_output=True, text=True).stdout.strip()
            why = []
            if out:
                why.append(f"{len(out.splitlines())} незапушених комітів")
            if dirty:
                why.append(f"{len(dirty.splitlines())} незакомічених файлів")
            if why:
                pending.append((r, ", ".join(why)))
        except Exception:
            pass
    if pending:
        print("\n  !! НЕ В ORIGIN — на інших машинах діятиме стара версія правил:")
        for r, why in pending:
            print(f"     {r}: {why}")
        print("     закоміть і запушіть (git push -u origin main, якщо upstream немає)")


if __name__ == "__main__":
    sys.exit(main())
